# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keshifbeta < Formula
  desc "proxy"
  homepage "https://github.com/gencdev/keshifbeta"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gencdev/keshifbeta/releases/download/v0.0.3/keshifbeta_0.0.3_macOS_x86_64.tar.gz"
      sha256 "80594688980deea7b119d19c7806f1abd7305b121df055ce415fdae053ad5541"

      def install
        bin.install "keshifbeta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gencdev/keshifbeta/releases/download/v0.0.3/keshifbeta_0.0.3_macOS_arm64.tar.gz"
      sha256 "f73b63f4bc0198ed731653d0917c3739474ebaee3d8a5f10d13423544c155c5d"

      def install
        bin.install "keshifbeta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gencdev/keshifbeta/releases/download/v0.0.3/keshifbeta_0.0.3_Linux_x86_64.tar.gz"
      sha256 "057876e9000b57247dc562268dd26dee5b1987366ab32c0dfcfecab2a89bab2c"

      def install
        bin.install "keshifbeta"
      end
    end
  end

  depends_on "git"
  depends_on "go"

  def caveats; <<~EOS
    proxy
  EOS
  end
end
